# Generated by Django 5.2.8 on 2025-12-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='time',
            new_name='time_created',
        ),
    ]
